services:
  - type: web
    name: sma-monitor
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ppda_core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sma-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.8

databases:
  - name: sma-db
    databaseName: sma_db
    user: sma_user