name: sma-monitor CI

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [gh-pages, docs]  # Ignore non-code branches

env:
  PYTHON_VERSION: 3.12
  DATABASE_URL: sqlite:///db.sqlite3  # Default for simplicity, can override

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Don't stop all jobs if one matrix job fails
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Test multiple Python versions

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            __pycache__/
            *.pyc
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          
      - name: Run migrations
        run: python manage.py migrate --noinput
        
      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run --source='.' manage.py test
          coverage report -m
          
      - name: Security check
        run: |
          pip install safety
          safety check --ignore=51457  # Ignore known false positives